[package]
name = "rpn-calc-rs"
version = "0.1.0"
authors = ["Vigdail <vigdail.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
